version: "3.9"

services:
  gateway:
    image: nginx:alpine
    ports: ["8080:80"]
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [catalog, auth, profiles, planner]
    networks: [backend]

  catalog:
    build: ./services/catalog
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080/catalog
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: catalog_db
      DB_USERNAME: postgres
      DB_PASSWORD: secret
    volumes:
      - ./services/catalog:/var/www/html
    command: sh -lc "php artisan key:generate --force && php -S 0.0.0.0:9000 -t public"
    depends_on: [db]
    networks: [backend]

  auth:
    build: ./services/auth
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080/auth
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: auth_db
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      JWT_SECRET: 10zFI1SZnvOExwt3CpzUO99ZweKgrL4GipKSnLZqN7IMPnY3VBN7Tdoez1FoPbON


      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME:
      MAIL_PASSWORD:
      MAIL_ENCRYPTION:
      MAIL_FROM_ADDRESS: noreply@example.test
      MAIL_FROM_NAME: "${APP_NAME}"

      # (pasirinktinai FE nuorodai reseto mygtuke)
      FRONTEND_URL: http://localhost:5173
    volumes:
      - ./services/auth:/var/www/html
    command: sh -lc "php artisan key:generate --force && php -S 0.0.0.0:9000 -t public"
    depends_on: [db, mailpit]
    networks: [backend]

  profiles:
    build: ./services/profiles
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080/profiles
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: profiles_db
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      JWT_SECRET: 10zFI1SZnvOExwt3CpzUO99ZweKgrL4GipKSnLZqN7IMPnY3VBN7Tdoez1FoPbON
    volumes:
      - ./services/profiles:/var/www/html
    command: sh -lc "php artisan key:generate --force && php -S 0.0.0.0:9000 -t public"
    depends_on: [db]
    networks: [backend]

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP
    networks: [backend]


  planner:
    build: ./services/planner
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080/planner
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: planner_db
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      JWT_SECRET: 10zFI1SZnvOExwt3CpzUO99ZweKgrL4GipKSnLZqN7IMPnY3VBN7Tdoez1FoPbON
    volumes:
      - ./services/planner:/var/www/html
    command: sh -lc "php artisan key:generate --force && php -S 0.0.0.0:9000 -t public"
    depends_on: [db]
    networks: [backend]


  payments:
    build: ./services/payments
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080/payments
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: payments_db
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      JWT_SECRET: 10zFI1SZnvOExwt3CpzUO99ZweKgrL4GipKSnLZqN7IMPnY3VBN7Tdoez1FoPbON
    volumes:
      - ./services/payments:/var/www/html
    command: sh -lc "php artisan key:generate --force && php -S 0.0.0.0:9000 -t public"
    depends_on: [db]
    networks: [backend]

  coach-plans:
    build: ./services/coach-plans
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080/coach-plans
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: coach_plans_db
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      JWT_SECRET: 10zFI1SZnvOExwt3CpzUO99ZweKgrL4GipKSnLZqN7IMPnY3VBN7Tdoez1FoPbON
    volumes:
      - ./services/coach-plans:/var/www/html
    command: sh -lc "php artisan key:generate --force && php -S 0.0.0.0:9000 -t public"
    depends_on: [db]
    networks: [backend]

  chat:
    build: ./services/chat
    working_dir: /var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080/chat
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: chat_db
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      JWT_SECRET: 10zFI1SZnvOExwt3CpzUO99ZweKgrL4GipKSnLZqN7IMPnY3VBN7Tdoez1FoPbON
    volumes:
      - ./services/chat:/var/www/html
    command: sh -lc "php artisan key:generate --force && php -S 0.0.0.0:9000 -t public"
    depends_on: [db]
    networks: [backend]

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init-multi-db.sql:/docker-entrypoint-initdb.d/init-multi-db.sql:ro
    networks: [backend]

volumes:
  db_data:

networks:
  backend: