version: "3.9"

services:
  gateway:
    image: nginx:alpine
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - catalog

  catalog:
    build: ./services/catalog
    environment:
      APP_ENV: local
      APP_KEY: base64:tempwillbeset
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080/catalog
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: fit
      DB_USERNAME: app
      DB_PASSWORD: app
      REDIS_HOST: cache
      REDIS_PORT: 6379
    volumes:
      - ./services/catalog:/var/www/html
    command: php -S 0.0.0.0:9000 -t public
    ports:
      - "9001:9000" # nebÅ«tina, bet patogu diagnostikai
    depends_on:
      - db
      - cache

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: fit
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  cache:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  dbdata:
